### ISSUE TITLE
Multi Processing system that is added in main py file is not functioning well!!!

### ISSUE THREAD

**Issue by iamEzmuth** [iamEzmuth/DeAuthImposter#2]
If you look at main py file, you will see multi-processing code that was written just in case if a new person joins the network after the attack is been proceeded than he/she will not be the victim of that attack.

But the code is not working, I created this script just for fun but now i am thinking of making it better so if anyone is interested than PRs are most welcome!

**Comment by 0xuser64bit** [comment]
Hey :wave: 
I've used your script a couple of times, I don't know if I'll be able to fully solve this problem but I wanna give it a shot.
Please assign me :smiley: 
Thank You :smile:

**Comment by iamEzmuth** [comment]
Sure, And Thanks for using this script, I am not a regular user of github but still fell free to make broken PRs and ask if any doubts, queries ,or code reviews.

**Comment by iamEzmuth** [comment]
I think so the issue has to be elaborated a little.
